typography_spectrum: 0.4831232214346528
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5659741761628538
  lightness: 0.45924201840534806
  saturation: 0.04585154773667455
  rhythmicContrast: 0.5747217191383243
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43379948334768414
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e7628b2f-abdf-42c3-9c3f-df6a9877288c.gif
name: renaultaustralia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
